# the name of Camel
camel:
  springboot:
    name: SampleCamel

greeting: Hello World

# how often to trigger the timer
timer:
  period: 10000

#swagger configuration
swagger:
  scheme: http

#webjars configuration
spring:
  resources:
    chain:
      enabled: true

#security.user.password=abcpass123
      
security:
  oauth2:
    client:
      clientId: source-microservice
      clientSecret: CLIENT_SECRET
      accessTokenUri: https://etbuaa.etbpoc.com/oauth/token
      userAuthorizationUri: https://etbuaa.etbpoc.com/oauth/authorize
      clientAuthenticationScheme: header
      authenticationScheme: query
      tokenName: oauth_token
      scope: uaa.user
      auto-approve-scopes: '.*'
    resource:
      userInfoUri: https://etbuaa.etbpoc.com/userinfo
      tokenInfoUri: https://etbuaa.etbpoc.com/check_token